Homework 3 done!
MINER9000/haskell-prog-home-work pull request #3
Opened 2018-07-25 15:46 UTC by MINER9000

Some usefull links:
[Homework condition](http://www.seas.upenn.edu/~cis194/spring13/hw/03-rec-poly.pdf)
[Homeworks](http://www.seas.upenn.edu/~cis194/spring13/lectures.html)

Waiting for [Dmitriy](https://github.com/ChShersh) to review my shit code :D

2018-07-26 03:03 UTC, chshersh requested changes

2018-07-26 03:03 UTC, ChShersh commented on src/Golf.hs
> +skips list = skipskip list (length list - 1)
Try to use more standard functions.

1. Write function `skipNth` which takes number `n` and remove every `n`th number from list. I see that your `skip` function does something similar. But it's more efficient to use standard functions. For `skipNth` you should use standard `splitAt` function:

* https://hackage.haskell.org/package/base-4.11.1.0/docs/Prelude.html#v:splitAt

2. Then You can apply `skipNth` function for every integer. Use `map` function for this. And probably something else.

2018-07-26 03:03 UTC, ChShersh commented on src/Golf.hs
> +localMaxima (x:y:z:xs) = [y | y > x && y > z] ++ localMaxima (y:z:xs)
This is a good solution! But you can use as-patterns to make it more ~scary~ shorter. Like this:

```haskell
localMaxima (x:xs@(y:z:_)) = [y | y > x && y > z] ++ localMaxima xs
```

2018-07-26 03:03 UTC, ChShersh commented on src/Golf.hs
> +count (x:xs) a0 a1 a2 a3 a4 a5 a6 a7 a8 a9 = case x of
This function is really ugly 😕 You shouldn't write such functions! Check documentation for `Data.List` module and see what you can use to make cleaner code.

* https://hackage.haskell.org/package/base-4.11.1.0/docs/Data-List.html

Probably you can find function like `transpose` useful:

* https://hackage.haskell.org/package/base-4.11.1.0/docs/Data-List.html#v:transpose

2018-07-26 03:03 UTC, ChShersh commented on src/Golf.hs
> +decMaxByOne :: [Integer] -> Integer -> [Integer]
`Integer` is not very efficient type. If you know that your input won't too big, it's better to use more compact types like `Int`.

2018-07-26 03:10 UTC, MINER9000 commented on src/Golf.hs
> +decMaxByOne :: [Integer] -> Integer -> [Integer]
I just always use Integer because I don't want to see exceptions that Integer doesn't match Int or something like that.

2018-07-26 03:40 UTC, ChShersh commented on src/Golf.hs
> +decMaxByOne :: [Integer] -> Integer -> [Integer]
It's okay for homeworks but in real life you should use efficient types if possible.

2018-07-29 05:24 UTC, chshersh approved these changes
Great! Some improvements can be made. But still quite good :) :+1:

2018-07-29 05:24 UTC, merged