Implemented HW6!
MINER9000/haskell-prog-home-work pull request #6
Opened 2018-09-28 13:50 UTC by MINER9000

All exercises except 6(optional)

2018-09-28 13:53 UTC, MINER9000 commented
[Homeworks](http://www.seas.upenn.edu/~cis194/spring13/lectures.html)

2018-09-29 13:56 UTC, chshersh requested changes

2018-09-29 13:56 UTC, ChShersh commented on src/Fibonacci.hs
> +newtype Stream a = Stream [a]
This definition is wrong. `Stream` should represent infinite number of elements. By haveing `Stream [a]` constructor, you're just having wrapper around list. This should be:

```haskell
data Stream a = Stream a (Stream a)
```

Now you have infinite stream of values :slightly_smiling_face:

2018-10-08 03:02 UTC, chshersh approved these changes
Looks good now!

2018-10-08 03:03 UTC, merged